"""initial schema

Revision ID: 3d65415b3ab1
Revises: 
Create Date: 2026-05-28 08:22:43.865753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d65415b3ab1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto_draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_no', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('number_1', sa.SmallInteger(), nullable=False),
    sa.Column('number_2', sa.SmallInteger(), nullable=False),
    sa.Column('number_3', sa.SmallInteger(), nullable=False),
    sa.Column('number_4', sa.SmallInteger(), nullable=False),
    sa.Column('number_5', sa.SmallInteger(), nullable=False),
    sa.Column('number_6', sa.SmallInteger(), nullable=False),
    sa.Column('bonus_number', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('number_1 < number_2 AND number_2 < number_3 AND number_3 < number_4 AND number_4 < number_5 AND number_5 < number_6', name='chk_numbers_sorted'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_no', name='uq_lotto_draw_no')
    )
    with op.batch_alter_table('lotto_draws', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lotto_draws_draw_no'), ['draw_no'], unique=False)

    op.create_table('number_statistics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=40), nullable=False),
    sa.Column('stat_range', sa.String(length=40), nullable=False),
    sa.Column('stat_data_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_type', 'stat_range', name='uq_stat')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('user_algorithm_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preset_name', sa.String(length=80), nullable=False),
    sa.Column('preset_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_algorithm_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_algorithm_presets_user_id'), ['user_id'], unique=False)

    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('recommended_numbers_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('algorithm_steps_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('filters_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['user_algorithm_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_history_created_at'))

    op.drop_table('recommendation_history')
    with op.batch_alter_table('user_algorithm_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_algorithm_presets_user_id'))

    op.drop_table('user_algorithm_presets')
    op.drop_table('users')
    op.drop_table('number_statistics_cache')
    with op.batch_alter_table('lotto_draws', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lotto_draws_draw_no'))

    op.drop_table('lotto_draws')
    # ### end Alembic commands ###
